### ISSUE TITLE
Missing using statement in FormWrapper.cshtml ?

### ISSUE THREAD

**Issue by KayeeNL** [Sitecore/Sitecore.HabitatHome.Corporate#2] opened 2019-08-02 15:39 UTC
Hi @jeanfrancoislarente, @IgorKorytko 

Getting an error when I go to https://habitathomecorporate.dev.local/Download-our-whitepaper: (same thing happens at https://habitathomecorporate.dev.local/About-Us/Contact-Us), 
----------
https://habitathomecorporate.dev.local/Download-our-whitepaper

Server Error in '/' Application.
Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS1061: 'System.Web.WebPages.Html.HtmlHelper' does not contain a definition for 'Sitecore' and no extension method 'Sitecore' accepting a first argument of type 'System.Web.WebPages.Html.HtmlHelper' could be found (are you missing a using directive or an assembly reference?)

Source Error:

Line 2:  
Line 3:  <div class="container">
Line 4:      @Html.Sitecore().DynamicPlaceholder("formwrapper")
Line 5:  </div>
Line 6:  

Source File: c:\inetpub\wwwroot\habitathomecorporate.dev.local\Areas\Forms\Views\FormWrapper\FormWrapper.cshtml    Line: 4

**Comment by KayeeNL** [comment] 2019-08-02 16:00
The reason i found out is: that the web.config is missing in the C:\inetpub\wwwroot\habitathomecorporate.dev.local\Areas\Forms\Views directory when you just run the build.ps1 script, without doing a build in VS2017.

Apparently it doesn't get installed when the nuget package is restored: \packages\sitecore.demo.feature.forms\9.2.0.36\contentFiles\any\any\Areas\Forms\Views

when i copy it over from the nuget package, the form is loading on the page without getting the exception.

**Comment by jflheureux** [comment] 2019-09-05 14:18
This issue was fixed internally. It was caused by a Cake deployment script that was ignoring this web.config file. The fix will be pushed to GitHub in about 2 weeks at the end of our current development sprint.

For the moment, use @KayeeNL's workaround.

**Closed as completed** 2019-09-05 14:19 UTC
